name: Cache Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: prime-cache-a4e4486
      uses: actions/cache@v4
      with:
        key: cache-a4e4486
        path: .cache-test
    - name: Create cache content
      run: mkdir -p .cache-test && echo "test-data" > .cache-test/file.txt
